parameters:
  model.doctrine.orm.default_repository_factory.class: Mediapark\MPDoctrineRepositoryExtensionBundle\ORM\Repository\MPDefaultRepositoryFactory
  model.doctrine.orm.repositories_resolver.class: Mediapark\MPDoctrineRepositoryExtensionBundle\ORM\Annotations\RepositoriesResolver
  doctrine.orm.entity_manager.class: Mediapark\MPDoctrineRepositoryExtensionBundle\ORM\MPEntityManager
  mp.doctrine.configuration.class_name: Mediapark\MPDoctrineRepositoryExtensionBundle\ORM\Configuration\MPConfiguration

services:
    mp.doctrine.configuration:
      class: Mediapark\MPDoctrineRepositoryExtensionBundle\ORM\Configuration\MPConfiguration

    doctrine.orm.entity_manager.abstract:
      class: "%doctrine.orm.entity_manager.class%"
      factory:  ["%doctrine.orm.entity_manager.class%", "customCreate"]
      #factory:  ['Mediapark\MPDoctrineRepositoryExtensionBundle\ORM\MPEntityManager', "customCreate"]
      abstract: true
      arguments:
        - "@mp.doctrine.configuration"
        - "@doctrine.dbal.default_connection"
        - "@doctrine.orm.default_configuration"
        - "@doctrine.dbal.event_manager"

    Mediapark\MPDoctrineRepositoryExtensionBundle\ORM\MpEntityManagerInterface:
        class: '%doctrine.orm.entity_manager.class%'
        parent: 'doctrine.orm.entity_manager.abstract'
